processed 3 tasks

init:
A: object(0,0)

task 1, lines 8-20:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4468800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 22-23:
//# programmable --sender A --inputs struct(fakeid(0,0),0)
//> 0: test::m::take_s(Input(0));
Error: Transaction Effects Status: Invalid command argument at 0. The argument cannot be instantiated from raw bytes
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidUsageOfPureArg }, source: Some("Non-primitive argument at index 0. If it is an object, it must be populated by an object"), command: Some(0) } }
